<?php

namespace ContainerYb6AzfV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HCR9GuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hC_R9Gu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hC_R9Gu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pacienteRepository' => ['privates', 'App\\Repository\\PacienteRepository', 'getPacienteRepositoryService', true],
        ], [
            'pacienteRepository' => 'App\\Repository\\PacienteRepository',
        ]);
    }
}
