<?php

namespace ContainerYb6AzfV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RPP0iV..App\Entity\Medico' shared service.
     *
     * @return \App\Entity\Medico
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RPP0iV.": it references class "App\\Entity\\Medico" but no such service exists.');
    }
}
