<?php

namespace ContainerYb6AzfV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MedicoType' shared autowired service.
     *
     * @return \App\Form\MedicoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MedicoType.php';

        return $container->privates['App\\Form\\MedicoType'] = new \App\Form\MedicoType();
    }
}
