<?php

namespace ContainerS6TDPTM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XBGrqZbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xBGrqZb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xBGrqZb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medico' => ['privates', '.errored..service_locator.xBGrqZb.App\\Entity\\Medico', NULL, 'Cannot autowire service ".service_locator.xBGrqZb": it references class "App\\Entity\\Medico" but no such service exists.'],
            'medicoRepository' => ['privates', 'App\\Repository\\MedicoRepository', 'getMedicoRepositoryService', true],
        ], [
            'medico' => 'App\\Entity\\Medico',
            'medicoRepository' => 'App\\Repository\\MedicoRepository',
        ]);
    }
}
