<?php

namespace ContainerS6TDPTM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RwD47CXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rwD47CX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rwD47CX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medicamento' => ['privates', '.errored..service_locator.rwD47CX.App\\Entity\\Medicamento', NULL, 'Cannot autowire service ".service_locator.rwD47CX": it references class "App\\Entity\\Medicamento" but no such service exists.'],
            'medicamentoRepository' => ['privates', 'App\\Repository\\MedicamentoRepository', 'getMedicamentoRepositoryService', true],
        ], [
            'medicamento' => 'App\\Entity\\Medicamento',
            'medicamentoRepository' => 'App\\Repository\\MedicamentoRepository',
        ]);
    }
}
