<?php

namespace ContainerS6TDPTM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicamentoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RN4Rt98.App\Entity\Medicamento' shared service.
     *
     * @return \App\Entity\Medicamento
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RN4Rt98": it references class "App\\Entity\\Medicamento" but no such service exists.');
    }
}
