<?php

namespace ContainerS6TDPTM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaciente2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ARt4mUO.App\Entity\Paciente' shared service.
     *
     * @return \App\Entity\Paciente
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ARt4mUO": it references class "App\\Entity\\Paciente" but no such service exists.');
    }
}
