<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS6TDPTM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS6TDPTM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS6TDPTM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS6TDPTM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS6TDPTM\App_KernelDevDebugContainer([
    'container.build_hash' => 'S6TDPTM',
    'container.build_id' => 'a7def8e7',
    'container.build_time' => 1656977905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS6TDPTM');
