<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_medicamento_index' => [[], ['_controller' => 'App\\Controller\\MedicamentoController::index'], [], [['text', '/medicamento/']], [], [], []],
    'app_medicamento_new' => [[], ['_controller' => 'App\\Controller\\MedicamentoController::new'], [], [['text', '/medicamento/new']], [], [], []],
    'app_medicamento_show' => [['id'], ['_controller' => 'App\\Controller\\MedicamentoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medicamento']], [], [], []],
    'app_medicamento_edit' => [['id'], ['_controller' => 'App\\Controller\\MedicamentoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/medicamento']], [], [], []],
    'app_medicamento_delete' => [['id'], ['_controller' => 'App\\Controller\\MedicamentoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medicamento']], [], [], []],
    'app_medico_index' => [[], ['_controller' => 'App\\Controller\\MedicoController::index'], [], [['text', '/medico/']], [], [], []],
    'app_medico_new' => [[], ['_controller' => 'App\\Controller\\MedicoController::new'], [], [['text', '/medico/new']], [], [], []],
    'app_medico_show' => [['id'], ['_controller' => 'App\\Controller\\MedicoController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medico']], [], [], []],
    'app_medico_edit' => [['id'], ['_controller' => 'App\\Controller\\MedicoController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/medico']], [], [], []],
    'app_medico_delete' => [['id'], ['_controller' => 'App\\Controller\\MedicoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medico']], [], [], []],
    'app_paciente_index' => [[], ['_controller' => 'App\\Controller\\PacienteController::index'], [], [['text', '/paciente/']], [], [], []],
    'app_paciente_new' => [[], ['_controller' => 'App\\Controller\\PacienteController::new'], [], [['text', '/paciente/new']], [], [], []],
    'app_paciente_show' => [['id'], ['_controller' => 'App\\Controller\\PacienteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/paciente']], [], [], []],
    'app_paciente_edit' => [['id'], ['_controller' => 'App\\Controller\\PacienteController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/paciente']], [], [], []],
    'app_paciente_delete' => [['id'], ['_controller' => 'App\\Controller\\PacienteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/paciente']], [], [], []],
];
